version : "3"
services:
  db:
    image: mysql:5.7.20
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env

    environment:
      MYSQL_DATABASE: wordpress_db
    networks:
      - wordpress-network
  web:
    depends_on:
      - db
    image: wordpress:4.8-apache
    container_name: wordpress 
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: admin@123
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress-network

volumes:
  db_data: {}
  wordpress_data: {}

networks:
  wordpress-network:
    driver: bridge
